const interests = [
  'fight club',
  'hiking',
  'walking',
  'partying',
  'museums',
  'galleries',
  'extreme sports',
  'tennis',
  'running',
  'cycling',
  'badminton',
  'table tennis',
  'board games',
  'eating out - veggie',
  'eating out - meat',
  'coffee',
  'beer',
  'urban exploring',
  'pokemon go',
  'cinema',
  'cocktails',
  'frisbee',
  'park hang',
  'picnic',
  'disc golf',
  'arts and crafts',
  'bowling',
  'cheese rolling',
  'shopping',
  'theme park',
  'tea ceremony',
  'gong bath',
  'yoga',
  'cooking'
]

export default interests;